# Apparently docker-compose doesn't work in Heroku. Oh well.
version: "3.9"
services:
  icw:
    platform: "linux/amd64"
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - "ICW_CONFIG=/etc/icw/prod_config.cfg"
    volumes:
      - "./prod_config.cfg:/etc/icw/prod_config.cfg:ro"
