---
permissions:
  contents: read
  pages: write
  id-token: write

name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build HTML
        run: make docs
      - uses: actions/upload-pages-artifact@v0.1.0
        with:
          path: docs/_build/html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy docs
        id: deployment
        uses: actions/deploy-pages@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
